### ISSUE TITLE
Kanban board set up - Group capstone 

### ISSUE THREAD

**Issue by tahseenzahra** [tahseenzahra/Capstone-Module2#21]
### For the Module 2; Group Capstone project, we have a team of 2 members

- [Tahseen Zahra](https://github.com/tahseenzahra)
- [Joel Kugonza](https://github.com/Joel-100)

[Here is the link to the GitHub project](https://github.com/users/tahseenzahra/projects/1)

**Comment by franclobo** [comment]
Hi @tahseenzahra and @Joel-100,

# STATUS: APPROVED 😃

Your project is complete!
Congratulations! 🎉

## Highlights

Good use of issues ✔️
All activities are assigned ✔️
